# Generated by Django 4.0.5 on 2022-06-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_userfollowing_unique_followers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_followers',
        ),
    ]
